import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from "./provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Root layout component that defines the application's HTML shell and font classes.
 *
 * Renders the top-level <html lang="en" suppressHydrationWarning> and <body> with
 * the configured Geist fonts and antialiasing, and places `children` inside the
 * app-wide Provider.
 *
 * @param {React.ReactNode} children - Content to render inside the layout (page/app content).
 * @returns {JSX.Element} The root HTML layout element.
 */
export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider>
          {children}
        </Provider>

      </body>
    </html>
  );
}
